// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FamilyGroup;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserRoot : GPBRootObject
@end

#pragma mark - Input

typedef GPB_ENUM(Input_FieldNumber) {
  Input_FieldNumber_Account = 1,
  Input_FieldNumber_Password = 2,
};

/**
 * 接收参数
 **/
@interface Input : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *account;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - Output

typedef GPB_ENUM(Output_FieldNumber) {
  Output_FieldNumber_UserId = 1,
  Output_FieldNumber_UserName = 2,
  Output_FieldNumber_Password = 3,
  Output_FieldNumber_Telephone = 4,
  Output_FieldNumber_Address = 5,
  Output_FieldNumber_Family = 6,
};

/**
 * 返回数据
 **/
@interface Output : GPBMessage

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite) int64_t telephone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, strong, null_resettable) FamilyGroup *family;
/** Test to see if @c family has been set. */
@property(nonatomic, readwrite) BOOL hasFamily;

@end

#pragma mark - FamilyGroup

typedef GPB_ENUM(FamilyGroup_FieldNumber) {
  FamilyGroup_FieldNumber_Father = 1,
  FamilyGroup_FieldNumber_Mother = 2,
};

@interface FamilyGroup : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *father;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mother;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
